[package]
name = "tezos_interop"
version = "0.0.1-pre16-context-poc"
authors = ["Tomas Sedlak <tomas.sedlak@simplestaking.com>"]
edition = "2018"

[dependencies]
futures-preview = "0.3.0-alpha.19"
hex = "0.4"
lazy_static = "1.4"
ocaml = "0.8.0"
# local dependencies
tezos_api = { path = "../api" }
tezos_context = { path = "../context" }

[build-dependencies]
colored = "1.8.0"
fs_extra = "1.1.0"
hex = "0.4"
os_type = "2.2.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
sha2 = "0.8.0"