[package]
name = "shell"
version = "0.1.0"
authors = ["Tomas Sedlak <tomas.sedlak@simplestaking.com>"]
edition = "2018"

[dependencies]
dns-lookup = "1.0.1"
failure = "0.1.5"
hex = "0.4.0"
itertools = "0.8.0"
log = "0.4.8"
rand = "0.7.2"
riker = { git = "https://github.com/riker-rs/riker" }
rocksdb = "0.12.3"
# local dependencies
networking = { path = "../networking" }
storage = { path = "../storage" }
tezos_encoding = { path = "../tezos_encoding" }
tezos_client = { path = "../tezos_client" }