[package]
name = "sandbox"
version = "0.6.0"
authors = ["Adrian Nagy <adrian.nagy@simplestaking.com>"]
edition = "2018"
default-run = "sandbox"

[dependencies]
chrono = { version = "0.4", features = ["serde"] }
failure = "0.1"
futures = "0.3"
hex = "0.4"
itertools = "0.9"
lazy_static = "1.4"
serde = { version = "1.0", features = ["derive", "rc"] }
serde_json = "1.0"
slog = { version = "2.5", features = ["nested-values"] }
slog-async = "2.5"
slog-term = "2.6"
tokio = { version = "0.2", features = ["macros"] }
warp = "0.2.4"
wait-timeout = "0.2"
nix = "0.17"
clap = "2.33"

[build-dependencies]
colored = "2.0"
hex = "0.4"
os_type = "2.2"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
sha2 = "0.9"