language: rust
rust:
  - nightly-2020-07-12

jobs:
  include:
  - os: linux
    dist: focal
    name: Ubuntu Focal (20.04)
  - os: osx
    name: macOS Catalina (10.15)
    osx_image: xcode12

sudo: false

env:
  global:
    - RUST_BACKTRACE=1
    - SODIUM_USE_PKG_CONFIG=1

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-trusty
    packages:
      - g++
      - llvm-dev
      - libclang-dev
      - clang
      - libsodium-dev
      - libev4
  homebrew:
    packages:
      - pkg-config
      - gmp
      - libev
      - libsodium

branches:
  only:
    - master
    - develop