version: "3"
services:

  node:
    image: simplestakingcom/tezedge
    build: ./docker/compose
    hostname: node
    ports:
      - "4927:4927"
      - "19732:9732"
      - "18732:18732"
    entrypoint: /home/appuser/tezedge/docker/compose/tezedge.sh
    tty: true
    
  explorer:
    image: simplestakingcom/tezedge-node-explorer
    hostname: explorer
    ports:
      - "8080:8080"
    tty: true
  