[package]
name = "logging"
version = "0.1.0"
authors = ["Tomas Sedlak <tomas.sedlak@simplestaking.com>"]
edition = "2018"


[dependencies]
chrono = "0.4.9"
nix = "0.15.0"
serde = { version = "1.0.101", features = ["derive"] }
slog = "2.5"
slog-async = "2.3"
slog-json = "2.3"
slog-term = "2.4"