[package]
name = "tezos_api"
version = "0.1.0"
authors = ["Tomas Sedlak <tomas.sedlak@simplestaking.com>"]
edition = "2018"

[dependencies]
derive-new = "0.5.8"
enum-iterator = "0.5.0"
failure = "0.1.5"
lazy_static = "1.4"
ocaml = "0.8.0"
serde = { version = "1.0", features = ["derive"] }
slog = "2.5"
# local dependencies
tezos_encoding = { path = "../encoding" }
tezos_messages = { path = "../messages" }