[package]
name = "networking"
version = "0.1.0"
authors = ["Tomas Sedlak <tomas.sedlak@simplestaking.com>"]
edition = "2018"

[dependencies]
bytes = "0.4.12"
dns-lookup = "1.0.1"
failure = "0.1.5"
futures-preview = "0.3.0-alpha.19"
hex = "0.4.0"
hyper = { git = "https://github.com/hyperium/hyper.git" }
riker = { git = "https://github.com/simplestaking/riker.git", branch = "slog-support" }
riker-patterns = "0.3.2"
slog = "2.5"
tokio = "0.2.0-alpha.6"
tokio-io = "0.2.0-alpha.6"
# local dependencies
tezos_encoding = { path = "../tezos/encoding" }
tezos_messages = { path = "../tezos/messages" }
crypto = { path = "../crypto" }
