[package]
name = "tezos_client"
version = "0.1.0"
authors = ["Branislav Kontur <branislav.kontur@simplestaking.com>"]
edition = "2018"

[dependencies]
dirs = "1.0.4"
failure = "0.1.5"
failure_derive = "0.1.5"
futures-preview = "0.3.0-alpha.19"
hex = "0.4.0"
lazy_static = "1.4.0"
serde = { version = "1.0.101", features = ["derive"] }
serde_json = "1.0.41"
slog = "2.5"
# local dependencies
tezos_encoding = { path = "../encoding" }
tezos_interop = { path = "../interop" }
tezos_messages = { path = "../messages" }