[package]
name = "tezos_interop_callback"
version = "0.5.0"
authors = ["Tomas Sedlak <tomas.sedlak@simplestaking.com>"]
edition = "2018"

[lib]
crate-type = ["dylib", "rlib"]

[dependencies]
ocaml-interop ={ git = "https://github.com/simplestaking/znfe.git", tag="v0.2.0" }
# local dependencies
tezos_context = { path = "../context" }
