[package]
name = "protocol_wrapper"
version = "0.1.0"
authors = ["Tomas Sedlak <tomas.sedlak@simplestaking.com>"]
edition = "2018"

[dependencies]
bincode = "1.2.0"
getset = { git = "https://github.com/Hoverbear/getset.git" }
failure = "0.1.5"
failure_derive = "0.1.5"
futures-preview = "0.3.0-alpha.19"
libc = "0.2.65"
rand = "0.7"
serde = { version = "1.0.101", features = ["derive"] }
slog = "2.5"
tokio = "0.2.0-alpha.6"
tokio-io = "0.2.0-alpha.6"
tokio-timer = "0.2.0-alpha.6"
# local dependencies
tezos_client = { path = "../client" }
tezos_interop = { path = "../interop" }
tezos_encoding = { path = "../encoding" }
tezos_messages = { path = "../messages" }
